---
title: "First Post"
date: 2018-09-19
output: html_document
---

This is my first post! I am very excited to start recording some of my work, thought processes, passion and excitement for data science and social policy. I plan to share R and Python code from projects I'm working on, books I'm reading, classes I'm taking... partly to be selfish and relearn the information by teaching it, but also hoping to reach people interested in (and new to) the intersection of data science and the policy/non-profit world. I was recently talking to an established non-profit in my area asking about their data analysis... They said they usually hand off the analysis to an intern or volunteer. Not that a voluteer or intern cannot have experience in these areas, but I hope to help show those involved in the non-profit space how much they can do with their data.

My posts may not always be explicitly policy-related, but I do always have the non-profit/policy perspective in the back of my mind. Please let me know if there are topics you are interested in seeing. Also, I would LOVE feedback on posts from those who have worked similar issues! There are always 100 ways to do things, so I want to hear your pros/cons/thoughts.

For my first project, I am thinking of looking at daycare options in Colorado. Quality daycare is important for so many reasons - not only providing children with a stable and nuturing environment, but giving the parents peace-of-mind and the ability to work. Unfortunately, access to quality daycare can be limited and/or EXPENSIVE. I have requested data from Colorado Shines Child Care Referral at Mile High United Way, but may have to start scraping...